// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCu_6GnUiMTDrwixaO_h159a5Zc0Uq3XqM',
    appId: '1:759389210814:android:bcb72438d62ef8863976ef',
    messagingSenderId: '759389210814',
    projectId: 'cardiocarequest',
    storageBucket: 'cardiocarequest.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkLHrKp1ET1UW0Xb9_eDxaIRmCP8oauCE',
    appId: '1:759389210814:ios:780a030c236bd49a3976ef',
    messagingSenderId: '759389210814',
    projectId: 'cardiocarequest',
    storageBucket: 'cardiocarequest.firebasestorage.app',
    iosBundleId: 'com.nau.cardiocarequest',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkLHrKp1ET1UW0Xb9_eDxaIRmCP8oauCE',
    appId: '1:759389210814:ios:780a030c236bd49a3976ef',
    messagingSenderId: '759389210814',
    projectId: 'cardiocarequest',
    storageBucket: 'cardiocarequest.firebasestorage.app',
    iosBundleId: 'com.nau.cardiocarequest',
  );

}